apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "misp.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "misp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "misp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "misp.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: misp-mysql-volume
            - mountPath: /var/www/MISP/app/Config
              name: misp-config-volume
      volumes:
        - name: misp-mysql-volume
          hostPath:
            path: {{ .Values.volumes.mysqlPath | quote }}
          type: Directory
        - name: misp-config-volume
          hostPath:
            path: {{ .Values.volumes.configPath | quote }}
          type: Directory
