apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: {{ template "misp.fullname" . }}
 labels:
   helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
   app.kubernetes.io/name: misp
   app.kubernetes.io/instance: {{ .Release.Name }}
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
 rules:
 - host: misp.enisa.ex
   http:
     paths:
     - backend:
         serviceName: misp-service
         servicePort: {{ .Values.service.port }}
