# Default values for nginx.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

# Evaluated by the post-install hook
sleepyTime: "10"

image:
  repository: harvarditsecurity/misp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8888
  nodePort: 30011

volumes:
  mysqlPath: /opt/enisa/trainings-2019/analyst/misp/data/misp-bare/misp2-bare-db
  configPath: /opt/enisa/trainings-2019/analyst/misp/data/misp-bare/misp2-bare-config
  mispData: /opt/enisa/trainings-2019/analyst/misp/data/misp-bare/misp2-bare-data

password: SecondInstancePassword123!
